spring:
  application:
    name: "Shiro"



shiro:
  ws:
    client:
      enable: true
      url: "ws://127.0.0.1:3001"


logging:
  config: classpath:log4j2.xml  # 指定 Log4j2 配置文件
  charset:
    console: UTF-8  # 强制控制台使用 UTF-8 编码
  file:
    charset: UTF-8  # 强制日志文件使用 UTF-8 编码


